# .github/workflows/deploy.yml
name: FastAPI Deployment

on:
  # Only trigger when code is merged to main branch
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to test server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.TEST_SERVER_HOST }}
        username: ${{ secrets.TEST_SERVER_USER }}
        password: ${{ secrets.TEST_SERVER_PASSWORD }}
        port: ${{ secrets.TEST_SERVER_PORT || 22 }}
