# .github/workflows/deploy.yml
name: FastAPI Deployment

on:
  # Only trigger when code is merged to main branch
  push:
    branches: [main]

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Execute remote SSH commands using password
          uses: appleboy/ssh-action@v1
          with:
            host: 192.168.2.218
            username: lanwa
            password: Welcome2025
            port: 22
            script: whoami
